-- AlterTable
ALTER TABLE "post" ALTER COLUMN "like" SET DEFAULT 0,
ALTER COLUMN "like" DROP DEFAULT,
ALTER COLUMN "dislike" SET DEFAULT 0,
ALTER COLUMN "dislike" DROP DEFAULT;
DROP SEQUENCE "post_like_seq";
DROP SEQUENCE "post_dislike_seq";

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "like" SET DEFAULT 0,
ALTER COLUMN "like" DROP DEFAULT,
ALTER COLUMN "dislike" SET DEFAULT 0,
ALTER COLUMN "dislike" DROP DEFAULT;
DROP SEQUENCE "user_like_seq";
DROP SEQUENCE "user_dislike_seq";
