
export const nichetype = [
  { label: 'Space' },
  { label: 'war' },
  { label: 'ocean' },
  { label: 'island' },
  { label: 'animal' },
  { label: 'world record' },
  { label: 'rocket' },
  { label: 'educational institute' },
  { label: 'vehicle' },
  { label: 'job' },
  {label:'solar system'},
  {label:'mars'},
  {label:'exoplanet'},
  {lable:'country'},
  {label:'ISRO'},
  {label:'foreign country'},
  {label:'satellite'},
  {label:'scientist'},
  {label:'Prime minister'},
  { label: 'sports' },
  { label: 'IPL' },
];