# name: Deploy backend1 and frontend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Log in to AWS ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Build, tag, and push backend image to ECR
#       run: |
#         cd backend
#         IMAGE_URI=<your-backend-ecr-uri>
#         docker build -t $IMAGE_URI:latest .
#         docker tag $IMAGE_URI:latest $IMAGE_URI:latest
#         docker push $IMAGE_URI:latest

#     - name: Build, tag, and push frontend image to ECR
#       run: |
#         cd frontend
#         IMAGE_URI=<your-frontend-ecr-uri>
#         docker build -t $IMAGE_URI:latest .
#         docker tag $IMAGE_URI:latest $IMAGE_URI:latest
#         docker push $IMAGE_URI:latest

#     - name: Deploy backend to ECS
#       run: |
#         aws ecs update-service --cluster <your-cluster-name> --service <your-backend-service-name> --force-new-deployment

#     - name: Deploy frontend to ECS
#       run: |
#         aws ecs update-service --cluster <your-cluster-name> --service <your-frontend-service-name> --force-new-deployment
